steps:
- id: 🤖 Code PR Creator - https://github.com/GoogleCloudPlatform/microservices-demo/pull/2438
  name: 'europe-docker.pkg.dev/coffee-and-codey/buildey-image/buildey:latest'
  args:
    - buildey
    - document
    - merge
    - -f 
    - "demo/sample-code/2438-diff.txt"
  allowFailure: true

- id: 🤖 Code review assistance - https://github.com/GoogleCloudPlatform/microservices-demo/pull/2438
  name: 'europe-docker.pkg.dev/coffee-and-codey/buildey-image/buildey:latest'
  args:
    - buildey
    - review
    - code
    - -f 
    - "demo/sample-code/2438-diff.txt"
  allowFailure: true

- id: 🤖 Release notes assistance - https://github.com/GoogleCloudPlatform/microservices-demo/pull/2438
  name: 'europe-docker.pkg.dev/coffee-and-codey/buildey-image/buildey:latest'
  args:
    - buildey
    - document
    - release
    - -f 
    - "demo/sample-code/2438-diff.txt"
  allowFailure: true

options:
  # logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  requestedVerifyOption: VERIFIED
  dynamicSubstitutions: true